nama = input("nama saya")
kelas = input("kelas saya")
umur = input("umur saya")
absen = input("absen saya")
hobi = input("hobi saya")
idola = input("idola saya")
hero = input("hero saya")
sekolah = input("sekolah saya") 
game = input("game apa")
print("halo nama saya",nama,"saya kelas",kelas,"umur saya",umur,"absen saya",absen,"hobi saya",hobi,"idola saya",idola,"hero saya",hero,"sekolah saya",sekolah,"game apa",game) 